# Description:
#   Go library providing support for making OAuth2-authenticated HTTP requests.

licenses(["notice"])  # New BSD License

exports_files(["LICENSE"])

package(default_visibility = ["//visibility:public"])
