# Description:
#    Go library providing support to accept sensitive input (e.g. passwords)
# from stdin.

licenses(["notice"])  # MIT

exports_files(["LICENSE"])

package(default_visibility = ["//visibility:public"])
