# Description:
#  Gorilla Websockets, a library for adding websocket support for the standard
#  Go web server

package(default_visiblity = ["//visibility:public"])

licenses(["notice"])

exports_files(["LICENSE"])
